project:
  type: website

website:
  title: "Guritlab"
  description: "Electronics, Data Science, and Machine Learning"
  site-url: https://ffazlurrahman.github.io
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ffazlurrahman
      - icon: rss
        href: index.xml

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

